In [1]:
%load_ext snakeviz
%snakeviz import optimized_script_speed_test


 Loading the sample runs:  44462-44463 


 Loading the empty runs:  43868-43911 

Data_ip first column: 
 [ 3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]
best fit parameters:
 [[  0.008   18.6752   3.4464   0.1268  20.      30.       0.2793  12.2     10.       1.2284   9.8      9.08  ]
 [  0.0163  17.      30.       0.2597  20.      30.       0.5722  12.2     -1.7496   1.4774  10.       0.381 ]
 [  0.0094  17.       0.7966   0.1502  20.      23.0643   0.3309  12.2    -10.       1.6154   9.8      0.2036]
 [  0.0135  17.      30.       0.2159  20.      30.       0.4756  12.2      2.6657   0.7438   9.8      5.9759]
 [  0.0185  20.     -30.       0.2945  25.     -30.       0.6488  18.      10.       1.5774  10.      -0.1528]
 [  0.      18.489   -0.3772   0.      22.6526  -0.3796   0.      15.9012   0.3254   0.       9.8      1.5956]
 [  0.0029  17.2856   0.2213   0.0468  20.       2.398    0.1031  12.2    -10.       0.5414

Data_ip first column: 
 [ 3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]
best fit parameters:
 [[  0.0076  18.6592   3.4332   0.1213  20.      30.       0.2673  12.2     10.       1.2009   9.8      9.1834]
 [  0.0163  17.      30.       0.2591  20.      30.       0.5708  12.2     -1.7775   1.4731  10.       0.3789]
 [  0.0092  17.       0.7528   0.1465  20.      22.7637   0.3227  12.2    -10.       1.5812   9.8      0.2295]
 [  0.0131  17.      30.       0.2083  20.      30.       0.4589  12.2      2.382    0.7025   9.8      6.0913]
 [  0.0177  20.     -30.       0.2815  25.     -30.       0.6202  18.      10.       1.4875  10.      -0.0989]
 [  0.      18.4885  -0.3624   0.      22.6527  -0.3691   0.      15.8927   0.3476   0.       9.8      1.5542]
 [  0.0031  17.       1.2003   0.0501  20.      24.9066   0.1103  12.2    -10.       0.5691   9.8     -7.5041]
 [  0.0244  20.     -30.       0.3888  25.     -30.       0.856

In [1]:
%load_ext snakeviz
%snakeviz import original_script_speed_test


 Fitting Workspace:  CePtGe12_100K_DD_

 Fitting parameters are given as: [Intensity Width Centre] for each NCP
3 [ 0.008  18.6779  3.4487  0.1269 20.     30.      0.2795 12.2    10.      1.2275  9.8     9.0807] 1.091
4 [ 0.0163 17.     30.      0.2597 20.     30.      0.5722 12.2    -1.7374  1.4773 10.      0.3805] 1.083
5 [  0.0094  17.       0.796    0.1502  20.      23.0544   0.3309  12.2    -10.       1.6154   9.8      0.2035] 0.9732
6 [ 0.0136 17.     30.      0.2159 20.     30.      0.4756 12.2     2.6731  0.7436  9.8     5.9772] 0.8458
7 [  0.0185  20.     -30.       0.2944  25.     -30.       0.6486  18.      10.       1.5777  10.      -0.1504] 0.8661
8 [ 0.     18.489  -0.3772  0.     22.6526 -0.3796  0.     15.9012  0.3254  0.      9.8     1.5956] 1.189
9 [  0.0029  17.2858   0.2244   0.0467  20.       2.3945   0.103   12.2    -10.       0.5416   9.8     -7.7224] 1.078
10 [  0.0257  20.     -30.       0.4094  25.     -30.       0.9021  15.923   10.       1.6732  10.      -1

76 [ 0.012  17.     30.      0.1916 20.     30.      0.4221 12.2    -4.8623  1.9243  9.8     3.0069] 1.067
77 [  0.0242  17.      -5.3476   0.3859  25.     -30.       0.8502  12.2    -10.       1.4706   9.8     -0.2067] 0.9839
78 [ 0.028  17.0081  1.0649  0.4457 20.     20.884   0.9819 18.     -6.9822  2.1029  9.8     2.0986] 0.9739
79 [  0.0194  17.7485  -0.5597   0.3087  25.      -9.178    0.6801  12.2    -10.       1.679    9.8     -9.5583] 0.9902
80 [  0.0242  19.9732  -1.2695   0.3856  25.     -30.       0.8496  12.2     -6.0763   1.8528  10.      -1.4309] 1.198
81 [ 0.0242 17.     30.      0.3857 20.     30.      0.8498 12.2    10.      2.2439  9.8    -0.2254] 1.146
82 [ 0.0176 17.4105  2.5472  0.281  20.     30.      0.6191 12.2    -3.4813  1.6603  9.8    -1.8777] 0.9817
83 [  0.0207  17.      -1.4868   0.3297  25.     -30.       0.7264  12.2    -10.       2.397    9.8     -0.9557] 1.121
84 [ 0.0315 20.      3.1095  0.5018 25.     29.88    1.1057 12.2    10.      1.971  10.     

In [1]:
%load_ext snakeviz
%snakeviz import My_edited_backward_script



 Loading the sample runs:  44462-44463 


 Loading the empty runs:  43868-43911 


 Fitting Workspace:  CePtGe12_100K_DD_0

 Fitting parameters are given as: [Intensity Width Centre] for each NCP
3 [ 0.008  18.6809  3.4472  0.1268 20.     30.      0.2794 12.2    10.      1.2278  9.8     9.0805] 1.091
4 [ 0.0163 17.     30.      0.2597 20.     30.      0.5722 12.2    -1.7361  1.4773 10.      0.3812] 1.083
5 [  0.0094  17.       0.7955   0.1502  20.      23.0555   0.3309  12.2    -10.       1.6154   9.8      0.2035] 0.9732

 intensities: 
 [[0.008  0.0163 0.0094    nan    nan]
 [0.1268 0.2597 0.1502    nan    nan]
 [0.2794 0.5722 0.3309    nan    nan]
 [1.2278 1.4773 1.6154    nan    nan]] 
 widths 
 [[18.6809 17.     17.         nan     nan]
 [20.     20.     20.         nan     nan]
 [12.2    12.2    12.2        nan     nan]
 [ 9.8    10.      9.8        nan     nan]] 
 positions 
 [[  3.4472  30.       0.7955      nan      nan]
 [ 30.      30.      23.0555      nan      nan]
 [ 10.  

In [1]:
import numpy as np

def load_ip_file(spectrum):
    """Instrument parameters of VESUVIO"""  
    
    #print "Loading parameters from file: ", namedtuple
    ipfile = r'C:\Users\guijo\Desktop\Work\ip2018.par'
    f = open(ipfile, 'r')
    data = f.read()
    lines = data.split('\n')
    for line in lines:       
        col = line.split('\t')
        if col[0].isdigit() and int(col[0]) == spectrum:
            angle = float(col[2])
            T0 = float(col[3])
            L0 = float(col[4])
            L1 = float(col[5])
    f.close()
    return angle, T0, L0, L1    
    
 
def load_ip_file_improved(spectrum):
    
    ipfile = r'C:\Users\guijo\Desktop\Work\ip2018.par'
    f = open(ipfile, 'r')
    data = f.read()
    lines = data.split("\n")[1:-1]  #take out the first line of non numbers and the last empty line
    data = list(map(lambda line: list(map(float, line.split("\t"))), lines))   #map is faster than for loops, list comprehension faster than map
    data = np.array(data)
    row = data[data[:, 0]==spectrum]
    angle, T0, L0, L1 = row[0, 2:]   #0 because its an array inside of an array
    return angle, T0, L0, L1

def load_ip_file_improved_2(spectrum):  
    ipfile = r'C:\Users\guijo\Desktop\Work\ip2018.par'
    f = open(ipfile, 'r')
    data = f.read()
    f.close()
    lines = data.split("\n")[1:-1]  #take out the first line of non numbers and the last empty line
    data_str = [line.split("\t") for line in lines]
    data = [[float(i) for i in line] for line in data_str]
    data = np.array(data)
    row = data[data[:, 0]==spectrum]
    angle, T0, L0, L1 = row[0, 2:]   #0 because its an array inside of an array
    return angle, T0, L0, L1
    

In [2]:
import cProfile, pstats
profiler = cProfile.Profile()
profiler.enable()
load_ip_file(150)
profiler.disable()
stats = pstats.Stats(profiler).sort_stats('cumtime')
stats.print_stats()

         451 function calls in 0.001 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        2    0.000    0.000    0.001    0.001 C:\MantidInstall\bin\lib\site-packages\IPython\core\interactiveshell.py:3281(run_code)
        2    0.000    0.000    0.001    0.000 {built-in method builtins.exec}
        1    0.000    0.000    0.001    0.001 <ipython-input-2-150d77bc3c6a>:4(<module>)
        1    0.000    0.000    0.001    0.001 <ipython-input-1-fe57aabf715f>:3(load_ip_file)
        1    0.000    0.000    0.000    0.000 {built-in method io.open}
        1    0.000    0.000    0.000    0.000 {method 'read' of '_io.TextIOWrapper' objects}
      199    0.000    0.000    0.000    0.000 {method 'split' of 'str' objects}
        2    0.000    0.000    0.000    0.000 C:\MantidInstall\bin\lib\codeop.py:132(__call__)
        2    0.000    0.000    0.000    0.000 {built-in method builtins.compile}
        1    0.000    0.000    0.000

In [6]:
import cProfile, pstats
profiler = cProfile.Profile()
profiler.enable()
load_ip_file_improved_2(150)
profiler.disable()
stats = pstats.Stats(profiler).sort_stats('cumtime')
stats.print_stats()

         254 function calls in 0.002 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        2    0.000    0.000    0.002    0.001 C:\MantidInstall\bin\lib\site-packages\IPython\core\interactiveshell.py:3281(run_code)
        2    0.000    0.000    0.002    0.001 {built-in method builtins.exec}
        1    0.000    0.000    0.002    0.002 <ipython-input-6-e5e3c0067b3b>:4(<module>)
        1    0.000    0.000    0.002    0.002 <ipython-input-5-77537ff58e9a>:34(load_ip_file_improved_2)
        1    0.000    0.000    0.001    0.001 <ipython-input-5-77537ff58e9a>:41(<listcomp>)
        1    0.000    0.000    0.000    0.000 {built-in method io.open}
        1    0.000    0.000    0.000    0.000 {method 'read' of '_io.TextIOWrapper' objects}
        1    0.000    0.000    0.000    0.000 <ipython-input-5-77537ff58e9a>:40(<listcomp>)
      197    0.000    0.000    0.000    0.000 {method 'split' of 'str' objects}
        1    0.0

In [2]:
%load_ext snakeviz
%snakeviz load_ip_file(150)

 
*** Profile stats marshalled to file 'C:\\Users\\guijo\\AppData\\Local\\Temp\\tmp0mwo25vd'. 
Embedding SnakeViz in this document...


In [3]:
%snakeviz load_ip_file_improved_2(134)

 
*** Profile stats marshalled to file 'C:\\Users\\guijo\\AppData\\Local\\Temp\\tmprkqxv2tz'. 
Embedding SnakeViz in this document...


In [1]:
#Example of a function that is now optimized, runs about 4 times faster

from mantid.simpleapi import *
import numpy as np

def normalise_workspace(ws_name):
    tmp_norm = Integration(ws_name)
    Divide(LHSWorkspace=ws_name,RHSWorkspace="tmp_norm",OutputWorkspace=ws_name)
    DeleteWorkspace("tmp_norm")
    
def convert_to_y_space_and_symmetrise_OPTIMIZED(ws_name,mass):  #Need to go over it
    """input: TOF workspace
       output: workspace in y-space for given mass with Ydata symetrised"""
          
    ws_y, ws_q = ConvertToYSpace(InputWorkspace=ws_name,Mass=mass,OutputWorkspace=ws_name+"_JoY",QWorkspace=ws_name+"_Q")
    max_Y = np.ceil(2.5*mass+27)    #where from
    rebin_parameters = str(-max_Y)+","+str(2.*max_Y/120)+","+str(max_Y)   #first bin boundary, width, last bin boundary, so 120 bins over range
    ws_y = Rebin(InputWorkspace=ws_y, Params = rebin_parameters, FullBinsOnly=True, OutputWorkspace=ws_name+"_JoY")
   
    matrix_Y = np.zeros((ws_y.getNumberHistograms(), ws_y.blocksize()))
    for spec_idx in range(len(matrix_Y)):                 #pass the y-data onto an array to easily manipulate
        matrix_Y[spec_idx, :] = ws_y.readY(spec_idx)        
    matrix_Y[matrix_Y != 0] = 1
    sum_Y = np.nansum(matrix_Y, axis=0)   
    ws_y = SumSpectra(InputWorkspace=ws_y, OutputWorkspace=ws_name+"_JoY")
    tmp=CloneWorkspace(InputWorkspace=ws_y)
    tmp.dataY(0)[:] = sum_Y
    tmp.dataE(0)[:] = np.zeros(tmp.blocksize())
    
    ws = Divide(LHSWorkspace=ws_y, RHSWorkspace=tmp, OutputWorkspace =ws_name+"_JoY")
    ws.dataY(0)[:] = (ws.readY(0)[:] + np.flip(ws.readY(0)[:])) / 2           #symetrise dataY
    ws.dataE(0)[:] = (ws.readE(0)[:] + np.flip(ws.readE(0)[:])) / 2           #sumetrise dataE
    normalise_workspace(ws)
    return max_Y 

def convert_to_y_space_and_symmetrise_ORIGINAL(ws_name,mass):  #Need to go over it       
    ws_y, ws_q = ConvertToYSpace(InputWorkspace=ws_name,Mass=mass,OutputWorkspace=ws_name+"_JoY",QWorkspace=ws_name+"_Q")    
    max_Y = np.ceil(2.5*mass+27)    #where from
    rebin_parameters = str(-max_Y)+","+str(2.*max_Y/120)+","+str(max_Y)   #first bin boundary, width, last bin boundary, so 120 bins over range
    ws = Rebin(InputWorkspace=ws_name+"_JoY", Params = rebin_parameters,FullBinsOnly=True, OutputWorkspace= ws_name+"_JoY")
    tmp=CloneWorkspace(InputWorkspace=ws_name+"_JoY")
    for j in range(tmp.getNumberHistograms()):
        for k in range(tmp.blocksize()):
            tmp.dataE(j)[k] =0.
            if (tmp.dataY(j)[k]!=0):
                tmp.dataY(j)[k] =1.
    tmp=SumSpectra('tmp')
    ws = SumSpectra(InputWorkspace=ws_name+"_JoY",OutputWorkspace=ws_name+"_JoY")
    ws = Divide(LHSWorkspace=ws_name+"_JoY", RHSWorkspace="tmp", OutputWorkspace =ws_name+"_JoY")
    ws=mtd[ws_name+"_JoY"]
    tmp=CloneWorkspace(InputWorkspace=ws_name+"_JoY")
    for k in range(tmp.blocksize()):
        tmp.dataE(0)[k] =(ws.dataE(0)[k]+ws.dataE(0)[ws.blocksize()-1-k])/2.
        tmp.dataY(0)[k] =(ws.dataY(0)[k]+ws.dataY(0)[ws.blocksize()-1-k])/2
    RenameWorkspace(InputWorkspace="tmp",OutputWorkspace=ws_name+"_JoY")
    normalise_workspace(ws_name+"_JoY")
    return max_Y

ws = Load("C:/Users/guijo/Desktop/Work/CePtGe12_backward_100K_scipy/CePtGe12_100K_DD_.nxs", OutputWorkspace="CePtGe12_100K_DD_.nxs")


In [3]:
import cProfile, pstats
profiler = cProfile.Profile()
profiler.enable()
convert_to_y_space_and_symmetrise_ORIGINAL(ws.name(), 140)
profiler.disable()
stats = pstats.Stats(profiler).sort_stats('cumtime')
stats.print_stats()

         13653 function calls (13643 primitive calls) in 0.138 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        2    0.000    0.000    0.139    0.069 C:\Users\guijo\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3400(run_code)
     12/2    0.001    0.000    0.139    0.069 {built-in method builtins.exec}
        1    0.000    0.000    0.139    0.139 <ipython-input-3-452a5c1803d3>:4(<module>)
        1    0.100    0.100    0.138    0.138 <ipython-input-1-6edfbddc3d8b>:34(convert_to_y_space_and_symmetrise_ORIGINAL)
       10    0.016    0.002    0.035    0.003 C:\Users\guijo\MantidInstall\bin\mantid\simpleapi.py:989(__call__)
       11    0.000    0.000    0.016    0.001 C:\Users\guijo\MantidInstall\bin\mantid\kernel\funcinspect.py:300(lhs_info)
       11    0.001    0.000    0.016    0.001 C:\Users\guijo\MantidInstall\bin\mantid\kernel\funcinspect.py:211(process_frame)
       11    0.002    0.000    0.0

In [4]:
%load_ext snakeviz
%snakeviz convert_to_y_space_and_symmetrise_ORIGINAL(ws.name(), 140)


 
*** Profile stats marshalled to file 'C:\\Users\\guijo\\AppData\\Local\\Temp\\tmpsqxv_h5o'. 
Embedding SnakeViz in this document...


In [5]:
%snakeviz convert_to_y_space_and_symmetrise_OPTIMIZED(ws.name(), 140)


 
*** Profile stats marshalled to file 'C:\\Users\\guijo\\AppData\\Local\\Temp\\tmphkq99s9b'. 
Embedding SnakeViz in this document...
